# generated : {{utcnow}}  // template : ./setup/Makefile.jinja2

down:
	docker-compose down

clean:
	docker-compose rm -f -v

{% for item in items %}
test_{{continent}}_{{item.iso}}:
	echo " Start test  {{continent}}_{{item.iso}} - {{item.name_en}} "
	docker-compose run --rm taginfo_job_{{continent}}_{{item.iso}} /osm/sh/osm_split.sh
	docker-compose run --rm taginfo_job_{{continent}}_{{item.iso}} /osm/sh/osm_jobinit.sh
	docker-compose run --rm taginfo_view_{{continent}}_{{item.iso}}

{% endfor %}

# generated : {{utcnow}}
